### ISSUE TITLE
Link for dataset:

### ISSUE THREAD

**Issue by na3na3e** [As-anonymus/TECHNO_SRM#1]
Sorry, the cardamage2-mrtqm dataset does not exist, has been deleted, or is not shared with you.

**Comment by As-anonymus** [comment]
You can select any dataset from Roboflow and combine coco dataset  for augmentation some links 
https://universe.roboflow.com/sai-lakkshmi/car-damage-assessment/dataset/4/download
https://universe.roboflow.com/sammy/damaged-vehicle-images
https://universe.roboflow.com/ali-osama-79dxy/car-damage-detection-ft9cy

**Comment by na3na3e** [comment]
Hello,

Thank you very much for your kind words and feedback. I'm glad to hear that you find the project useful and well-developed.

Regarding the issue you mentioned about Multiple Image Detection, it seems that the display of the results after detection is currently similar to the one for video testing, rather than the expected output for single image detection. I apologize for any confusion caused by this.

To assist you further, could you please provide me with the code you are using for Multiple Image Detection? This will allow me to investigate the issue and provide you with a more accurate solution. Once I have more details, I'll be able to help you troubleshoot and resolve the problem.

Thank you for your understanding, and I look forward to assisting you. Have a great day!

Best regards,


________________________________
De : Aditya Singh ***@***.***>
Envoyé : vendredi 26 mai 2023 11:33
À : As-anonymus/TECHNO_SRM ***@***.***>
Cc : na3na3e ***@***.***>; Author ***@***.***>
Objet : Re: [As-anonymus/TECHNO_SRM] Link for dataset: (Issue #1)


You can select any dataset from Roboflow and combine coco dataset for augmentation some links
https://universe.roboflow.com/sai-lakkshmi/car-damage-assessment/dataset/4/download
https://universe.roboflow.com/sammy/damaged-vehicle-images
https://universe.roboflow.com/ali-osama-79dxy/car-damage-detection-ft9cy
